// Add your code here
maqueen.motorRun(maqueen.Side.Left, maqueen.Dir.CW, 100)
basic.pause(1000)
maqueen.motorRun(maqueen.Side.Left, maqueen.Dir.CW, 100)
basic.pause(1000)
maqueen.motorRun(maqueen.Side.Both, maqueen.Dir.CW, 100)
basic.pause(1000)
maqueen.servoRun(maqueen.Servos.S1, 90)
basic.pause(1000)
maqueen.servoRun(maqueen.Servos.S2, 90)
basic.pause(1000)
maqueen.motorStop(maqueen.Side.Left)
basic.pause(1000)
maqueen.motorStop(maqueen.Side.Right)
basic.pause(1000)
maqueen.motorStop(maqueen.Side.Both)
basic.pause(1000)
maqueen.writeLED(maqueen.Side.Left,maqueen.State.On)
basic.pause(1000)
maqueen.writeLED(maqueen.Side.Left,maqueen.State.Off)
basic.pause(1000)
maqueen.writeLED(maqueen.Side.Right,maqueen.State.On )
basic.pause(1000)
maqueen.writeLED(maqueen.Side.Right,maqueen.State.Off)
serial.writeLine("L:" + maqueen.readPatrol(maqueen.Side.Left))
basic.pause(1000)
serial.writeLine("R:" + maqueen.readPatrol(maqueen.Side.Right))
basic.pause(1000)
serial.writeLine("IR:" + maqueen.IR_read())
basic.pause(1000)
serial.writeLine("V:" + maqueen.IR_read_version())
basic.pause(1000)
serial.writeLine("CM:" + maqueen.Ultrasonic(maqueen.PingUnit.Centimeters))
basic.pause(1000)

